### ISSUE TITLE
zuletzte aktualisiert timestamp

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/phpdoc#13]
wäre schön wenn man in der seite irgendwo sehen könnte wann die docs zuletzt generiert wurden ... "Zuletzt aktualisiert am" o.ä.

**Comment by bloep** [comment]
ist unten auf der Seite ersichtlich
![image](https://user-images.githubusercontent.com/21292755/77226131-3b189080-6b76-11ea-8862-a9b7e6b9e9ff.png)
