### ISSUE TITLE
Falsche return types?

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/phpdoc#17]
Woher kommt das mixed?

![image](https://user-images.githubusercontent.com/120441/77226996-b1b88c80-6b7c-11ea-8c17-d6db35c151ba.jpeg)

**Comment by bloep** [comment]
`mixed` ist scheinbar hier automatisch für alles, die keinen expliziten return-type angegeben haben. 
im code sieht die Methode so aus:
![image](https://user-images.githubusercontent.com/21292755/77227639-07dbfe80-6b82-11ea-9b13-209fb3cbdd31.png)
