### ISSUE TITLE
rex_sql fehlt in der doku

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/phpdoc#27]
gemelet in slack

> Warum finde ich eigentlich in der api-Doku https://friendsofredaxo.github.io/phpdoc/ nirgends rex_sql?

hmm ?

![grafik](https://user-images.githubusercontent.com/120441/109168152-d18a0480-777e-11eb-9916-3d4102dcf8da.png)

**Comment by alxndr-w** [comment]
https://friendsofredaxo.github.io/phpdoc/classes/rex-sql.html
