### ISSUE TITLE
Ipad/tablet layout

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/phpdoc#3]
Zuerst einmal ein großes Dankeschön, dass du Dich diesem Thema annimmst Marcel 😘

Das layout ist ein wenig verschoben auf dem ipad (iOS 13.1.2)
![091C3DF3-B246-41BF-A5D4-6EB1FF1A594F](https://user-images.githubusercontent.com/120441/65909202-604af400-e3c8-11e9-96a2-104739a6af4a.png)

**Comment by bloep** [comment]
Danke für die Info.

ich persönlich finde das Theme von dem was phpdoc von Haus aus mitbringt am besten. Wobei ich das ursprüngliche Theme (http://redaxo.org/api/master/) noch besser finde. Überlege aktuell das evt. zu portieren.

Könnte also noch sein, dass sich das Theme/Template noch einmal komplett ändert.

**Comment by staabm** [comment]
Tablet ist auch nicht wichtig... wollte es nur festhalten.

Falls du das template ändern willst/kannst gerne
