### ISSUE TITLE
Quer verlinken

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/phpdoc#5]
Aus den FOR Seiten?
Von redaxo.org?

**Comment by staabm** [comment]
@schuer meinungen dazu?

**Comment by bloep** [comment]
ich würde die alte Location http://redaxo.org/api/ zu Github-Pages weiterleiten lassen, sobald der Stand hier "reifer" ist.
In der Doku auf redaxo.org gibt es ja schon eine Verknüpfung.

**Comment by staabm** [comment]
Find ich eine super idee!
