### ISSUE TITLE
Als "internal" markierte Klassen ignorieren

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/phpdoc#8]
Es wäre schön, wenn die Klassen, die mit `@internal` markiert sind, wieder ignoriert werden würden.

Laut https://docs.phpdoc.org/references/phpdoc/tags/internal.html#effects-in-phpdocumentor müssten sie auch ignoriert werden, wenn man `--parseprivate` weglässt. Warum haben wir die Option im Moment drin?

**Comment by bloep** [comment]
> Warum haben wir die Option im Moment drin?

hatte ich zu Testzwecken aufgenommen. Danke für den Hinweis.

**Comment by bloep** [comment]
die scheinen nicht mehr drin zu sein.
